using super in robot and commands
PilzDE/pilz_industrial_motion pull request #116
Opened 2019-03-14 09:18 UTC by rfeistenauer

This should fix Issue #115

2019-03-14 10:00 UTC, rfeistenauer commented on pilz_robot_programming/src/pilz_robot_programming/robot.py
> +        super(Robot, self).__init__()
probalby it should even be 
```
def __init__(*args, version=None, **kwargs)
    super(Robot, self).__init__(*args, **kwargs)
```

2019-03-14 10:10 UTC, agutenkunst commented
There are checks failing. Could you check on this?

2019-03-14 10:12 UTC, agutenkunst commented
There is a typo in the first commit and maybe add "Closes" for automatic issue closing in your commit.

2019-03-20 13:27 UTC, rfeistenauer commented
```
class Ptp(_BaseCmd):
    """
    ...
    """
    def __init__(self, acc_scale=None, vel_scale=None, *args, **kwargs):      
        acc_scale_final = acc_scale if acc_scale is not None else Ptp._calc_acc_scale(vel_scale)        
        super(Ptp, self).__init__(acc_scale=acc_scale_final, vel_scale=vel_scale, *args, **kwargs)
```
Depending on whether you want it for documentation reasons or not, you could even throw out all kwargs out of the command classes Ptp, Lin and Circ. They will still show on code completion hint since super takes care of that, but the doc above the classes may look off place.

2019-03-20 14:21 UTC, ct2034 requested changes
I think it would make sense to also remove the explicit params in the inheriting classes (when calling inti with super)

2019-03-20 15:31 UTC, ct2034 approved these changes

2019-03-20 15:32 UTC, ct2034 commented
@agutenkunst @hslusarek @martiniil Do we want this?

2019-03-22 07:05 UTC, martiniil reviewed
I don't see why someone would inherit from the Robot class multiple times. For single inheritance super() in the base class has no effect, right?
 
@rfeistenauer What are your thoughts on that?

2019-03-25 05:36 UTC, martiniil commented
I got it.

2019-03-25 05:41 UTC, merged

2019-03-25 06:27 UTC, rfeistenauer commented
just for documentation purpose: https://www.youtube.com/watch?v=EiOglTERPEo answeres this question