using getSingleDOFJointModels instead of  getActiveJointModels to support mimic joints
PilzDE/pilz_industrial_motion pull request #121
Opened 2019-03-18 15:37 UTC by mmoerdijk

Using getSingleDOFJointModels instead of  getActiveJointModels to support mimic joints. Without this change the planner crashes when looking for the joint limits of the mimic joints.

2019-03-19 12:26 UTC, jschleicher commented
What configuration are you using? Could you add the config where the planner crashes?
Best would be a test case that fails with the current implementation and passes with your fix.

2019-03-19 13:01 UTC, mmoerdijk commented
Good idea I will look into making a simple test case

2019-03-19 14:53 UTC, jschleicher commented
Thank you!

2019-03-20 14:23 UTC, ct2034 requested changes
@mmoerdijk 

@jschleicher:
> What configuration are you using? Could you add the config where the planner crashes?
> Best would be a test case that fails with the current implementation and passes with your fix.

2019-05-16 11:26 UTC, agutenkunst commented
@mmoerdijk ping

2019-05-23 11:16 UTC, martiniil commented
No progress since 2 months. Closing for now. Feel free to re-open.

2019-05-23 11:16 UTC, closed without merging