Add possibility to combine ptp and a relative lin into a blendable sequence.
PilzDE/pilz_industrial_motion pull request #245
Opened 2020-02-13 13:04 UTC by DanBmh

2020-02-14 10:56 UTC, ct2034 requested changes
This looks like a great addition. Thanks
To merge it, we need a test, though. Here [test/integrationtests/tst_api_cmd_conversion.py](https://github.com/PilzDE/pilz_industrial_motion/blob/melodic-devel/pilz_robot_programming/test/integrationtests/tst_api_cmd_conversion.py) and here [test/acceptance_tests/acceptance_test_blending.py](https://github.com/PilzDE/pilz_industrial_motion/blob/melodic-devel/pilz_robot_programming/test/acceptance_tests/acceptance_test_blending.py)

2020-02-14 10:56 UTC, ct2034 commented on pilz_trajectory_generation/src/joint_limits_container.cpp
> +  bool limit_ok = (!(hasLimit(joint_name)
This is also a good contribution in terms of verbosity. But can you please separate into an extra pr.

2020-02-14 10:56 UTC, ct2034 commented on pilz_robot_programming/src/pilz_robot_programming/commands.py
> +from moveit_msgs.msg import RobotState
Please combine these

2020-02-17 13:57 UTC, DanBmh commented
Im not sure how to test my blend sequence test, because for me it seems that i need a pilz robot for this.

2023-01-27 14:27 UTC, closed without merging