Use new coverage feature of ros_pytest
PilzDE/pilz_industrial_motion pull request #316
Opened 2020-09-10 07:43 UTC by martiniil

Closes #289

2020-09-15 08:58 UTC, ct2034 requested changes

2020-09-15 08:58 UTC, ct2034 commented on pilz_store_positions/CMakeLists.txt
> -  file(GLOB integrationtest_files "test/integrationtests/*.test")
What happened to the integration tests?

2020-09-15 11:53 UTC, martiniil commented on pilz_store_positions/CMakeLists.txt
> -  file(GLOB integrationtest_files "test/integrationtests/*.test")
There are none.

2020-10-01 11:14 UTC, hslusarek approved these changes

2020-10-01 11:15 UTC, merged