Fix/ik self collision/issue 29
PilzDE/pilz_industrial_motion pull request #37
Opened 2018-12-04 15:36 UTC by rfeistenauer

Fixes the problem, that self collision only throws error instead of searching for an alternative solution.

2018-12-11 14:13 UTC, jschleicher requested changes
Please address the comments.

Did you check code coverage and static analysis with klocwork or should I do that as part of the review?

2018-12-11 14:13 UTC, jschleicher commented on pilz_trajectory_generation/test/unittest_trajectory_functions.cpp
> +// Instantiate the test cases for robot model with and without gripper
comment: copy'n'paste error?

2018-12-11 14:13 UTC, jschleicher commented on pilz_trajectory_generation/test/unittest_trajectory_functions.cpp
> +#include <moveit/planning_scene/planning_scene.h>
Where is the include `planning_scene` used?

2018-12-11 14:13 UTC, jschleicher commented on pilz_trajectory_generation/include/pilz_trajectory_generation/trajectory_functions.h
> +                   double timeout = 0.005);
is this in seconds? Are 5 milliseconds a good default for all platforms?
Usually named constants are preferred over magic numbers.

2018-12-11 14:13 UTC, jschleicher commented on pilz_trajectory_generation/include/pilz_trajectory_generation/trajectory_functions.h
> + * @param test_for_self_collision Flag to deactivate this check during IK.
documentation does not match the function signature.

2018-12-11 14:13 UTC, jschleicher commented on pilz_trajectory_generation/src/trajectory_functions.cpp
>    // TODO: Should consider self collision already.
could you remove the TODO note now?

2018-12-11 14:13 UTC, jschleicher commented on pilz_trajectory_generation/test/unittest_trajectory_functions.cpp
> +                                  1));
Having a closer look this seems to rely on odd behaviour of the IK plugin. There was an upstream [PR](https://github.com/ros-planning/moveit/pull/585) and I think, we should re-generate the ikfast_plugin from the current template there. Then the collision-free solution should be delivered on the first attempt (without involving random seeds making the number of calls non-deterministic).

Could you think of another way to implement this "fail without collision check"-test?

2018-12-11 15:39 UTC, rfeistenauer commented on pilz_trajectory_generation/include/pilz_trajectory_generation/trajectory_functions.h
> +                   double timeout = 0.005);
the 5 ms were suggested somewhere on the web. 10 * 5 ms => min 20 Hz which was supposed to be an acceptable speed. Don't think i can find the quote quickly. The max attempts have been magic number already, thought you preferred it in the header for code api reasons maybe. Can change it if neccessary

2018-12-12 07:36 UTC, rfeistenauer commented
Checked code coverage. Its 100%
Never did the klocwork check so i would suggest either you do it, or you point me to a tutorial / explain it.

2018-12-20 10:33 UTC, jschleicher approved these changes

2018-12-20 13:13 UTC, merged