Assert in test that service is available
PilzDE/pilz_industrial_motion pull request #45
Opened 2019-01-04 10:02 UTC by agutenkunst

Make sure that services are up before using them. Tests need to be aborted if not.

2019-01-04 10:48 UTC, martiniil requested changes

2019-01-04 10:48 UTC, martiniil commented on pilz_trajectory_generation/test/integrationtest_command_planning.cpp
> +  ASSERT_TRUE(ros::service::waitForService(PLAN_SERVICE_NAME, ros::Duration(10)));
Use testutils::DEFAULT_SERVICE_TIMEOUT everywhere?

2019-01-08 08:33 UTC, agutenkunst commented on pilz_trajectory_generation/test/integrationtest_command_planning.cpp
> +  ASSERT_TRUE(ros::service::waitForService(PLAN_SERVICE_NAME, ros::Duration(10)));
Done.

2019-01-09 14:25 UTC, martiniil commented
In log of https://travis-ci.org/PilzDE/pilz_industrial_motion/jobs/477346308:

> [DEBUG] [1547041875.423349531]: searchPositionIK2: Position request pose is 0.313627 0.178519 0.355369 -1 -1.16029e-07 5.43542e-07 9.09851e-08
> [DEBUG] [1547041875.423390566]: IK timed out

In this case a second attempt uses random seed values, leading to our problem:
http://docs.ros.org/kinetic/api/moveit_core/html/robot__state_8cpp_source.html#l01619

So far my understanding. The timeout is defined in pilz_trajectory_generation/trajectory_functions.h:
`const double timeout = 0.005`

2019-01-21 08:05 UTC, martiniil approved these changes

2019-01-21 08:42 UTC, martiniil commented
@agutenkunst Do you approve these changes, too?

2019-01-21 09:49 UTC, merged