Refactor/blender transition window
PilzDE/pilz_industrial_motion pull request #58
Opened 2019-01-22 14:46 UTC by martiniil

* minor changes in computing trajectory alignment
* comment fixes

2019-01-23 12:50 UTC, agutenkunst commented on pilz_trajectory_generation/src/trajectory_blender_transition_window.cpp
> -  if(tau_1 > tau_2)
Does this now only work if both trajectories are equally discretized?

2019-01-23 12:50 UTC, agutenkunst requested changes
See comments

2019-01-24 06:25 UTC, martiniil commented on pilz_trajectory_generation/src/trajectory_blender_transition_window.cpp
> -  if(tau_1 > tau_2)
Yes, but this was always the case for the blend method. We just did not exploit it here.

2019-01-24 06:28 UTC, martiniil commented on pilz_trajectory_generation/src/trajectory_blender_transition_window.cpp
> -  if(tau_1 > tau_2)
See validateRequest():
https://github.com/PilzDE/pilz_industrial_motion/blob/18a26a448226a68abb51f2ad74352a456d1a5ccf/pilz_trajectory_generation/src/trajectory_blender_transition_window.cpp#L149

2019-01-24 07:27 UTC, agutenkunst commented on pilz_trajectory_generation/src/trajectory_blender_transition_window.cpp
> -  if(tau_1 > tau_2)
ok

2019-01-24 07:27 UTC, agutenkunst approved these changes

2019-01-28 06:24 UTC, agutenkunst approved these changes

2019-01-28 06:42 UTC, agutenkunst commented on pilz_trajectory_generation/include/pilz_trajectory_generation/trajectory_blender_transition_window.h
> +   * Let tau_1 be the time of the first trajectory from the first_interse_index to the end and tau_2 the time of the
Please check the resulting generated html documentation...

2019-01-28 06:42 UTC, agutenkunst requested changes
Please recheck the documentation

2019-01-29 09:40 UTC, agutenkunst approved these changes

2019-01-29 09:40 UTC, merged