WIP: Refactor/testdataloader classes
PilzDE/pilz_industrial_motion pull request #65
Opened 2019-01-30 06:39 UTC by hslusarek

2019-01-30 07:07 UTC, agutenkunst requested changes
Is diag_class_builder.png still relevant?

2019-01-30 07:25 UTC, agutenkunst commented on pilz_industrial_motion_testutils/doc/README.md
>  nochmal im Team über die Güte der neuen Daten diskutieren zu können.
1. Remove the german part here.
2. Add basic instructions on using the given functions

2019-01-30 07:25 UTC, agutenkunst commented on pilz_industrial_motion_testutils/doc/diagrams/diag_class_circ_auxiliary.uxf
> +    <panel_attributes>template=ConfigTypee&gt;
Typo

2019-01-30 08:29 UTC, agutenkunst requested changes

2019-01-30 08:29 UTC, agutenkunst commented on pilz_industrial_motion_testutils/include/pilz_industrial_motion_testutils/circ.h
> +  planning_interface::MotionPlanRequest req;
There is some code duplication here. I suggest putting most of these line into the base class to highlight the similarities. Please think about a std::string getPlannerId() = 0 in the base class .

2019-01-30 08:29 UTC, agutenkunst commented on pilz_industrial_motion_testutils/include/pilz_industrial_motion_testutils/center.h
> +  return BuilderType().setConstraintName("center")
How about a `getConstraintName` Name in the derived class and the rest inside the base class

2019-02-01 08:11 UTC, agutenkunst requested changes

2019-02-01 08:11 UTC, agutenkunst commented on pilz_industrial_motion_testutils/include/pilz_industrial_motion_testutils/motionplanrequestconvertible.h
> +class MPReqConvertible
Please rethink the classname. Maybe `MotionPlanRequestConvertible` ?

2019-02-01 08:11 UTC, agutenkunst commented on pilz_industrial_motion_testutils/include/pilz_industrial_motion_testutils/robotconfiguration.h
> +  throw std::runtime_error("Function 'toConstraints()' not implemented");
Could you add a bit more explanation for the reasoning behind this line considering the architecture?

2019-02-01 08:11 UTC, agutenkunst commented on pilz_industrial_motion_testutils/include/pilz_industrial_motion_testutils/sequence.h
> +  void add(MotionCmdUPtr cmd, double radius = 0.);
maybe `blend_radius` as parameter to be consistent with pilz_robot_programming?

2019-02-01 08:11 UTC, agutenkunst commented on pilz_industrial_motion_testutils/include/pilz_industrial_motion_testutils/sequence.h
> +  assert(cmd);
How about a `nullptr` check?

2019-02-01 08:11 UTC, agutenkunst commented on pilz_industrial_motion_testutils/include/pilz_industrial_motion_testutils/testdata_loader.h
>    virtual bool getJoints(const std::string &pos_name, const std::string &group_name,
You add a new `pose_name` while the old code has `pos_name`.

2019-02-01 08:11 UTC, agutenkunst commented on pilz_industrial_motion_testutils/include/pilz_industrial_motion_testutils/testdata_loader.h
> +   * DEPRECATED
http://www.doxygen.nl/manual/commands.html#cmddeprecated

2019-02-01 08:11 UTC, agutenkunst commented on pilz_industrial_motion_testutils/include/pilz_industrial_motion_testutils/testdata_loader.h
> +   * DEPRECATED
Or there seems to be something like `ROS_DEPRECATED`

2019-02-01 08:11 UTC, agutenkunst commented on pilz_industrial_motion_testutils/src/cartesianconfiguration.cpp
> +  // set the joints as ik seed
Not true anymore...

2019-02-01 08:11 UTC, agutenkunst commented on pilz_industrial_motion_testutils/src/jointconfiguration.cpp
> +                                                                    const std::vector<double>& config)
Indention problematic

2019-02-01 08:11 UTC, agutenkunst commented on pilz_industrial_motion_testutils/src/jointconfiguration.cpp
> +                                                                    const std::vector<double>& config,
Indention problematic

2019-02-01 08:11 UTC, agutenkunst commented on pilz_industrial_motion_testutils/src/jointconfiguration.cpp
> +  assert(robot_model_);
Maybe throw runtime_error?

2019-02-01 08:11 UTC, agutenkunst commented on pilz_industrial_motion_testutils/src/sequence.cpp
> +  for (auto& cmd : cmds_)
std::for_each should work as well

2019-02-01 08:11 UTC, agutenkunst commented on pilz_industrial_motion_testutils/src/xml_testdata_loader.cpp
> +    std::unique_ptr<CmdType> cmd_ptr { new CmdType() };
Explain the need to avoid slicing.

2019-02-01 08:11 UTC, agutenkunst commented on pilz_trajectory_generation/test/integrationtest_sequence_action_capability.cpp
> + * @brief  TODO
!

2019-02-01 08:43 UTC, hslusarek commented on pilz_industrial_motion_testutils/include/pilz_industrial_motion_testutils/sequence.h
> +  assert(cmd);
I don't understand. Do you want an exception instead?

2019-02-01 10:21 UTC, agutenkunst approved these changes

2019-02-01 10:21 UTC, merged