Fix/instance not cleared
PilzDE/pilz_industrial_motion pull request #66
Opened 2019-01-30 09:02 UTC by martiniil

2019-01-31 15:24 UTC, agutenkunst requested changes

2019-01-31 15:24 UTC, agutenkunst commented on pilz_robot_programming/src/pilz_robot_programming/robot.py
> +                os.kill(pid, 0)
What signal does 0 correspond to ?

2019-01-31 15:24 UTC, agutenkunst commented on pilz_robot_programming/src/pilz_robot_programming/robot.py
> +        # If no exception has been raised, the pid and create_time is stored (overwrites old one)
if(_check_single_instance()) would be more readable, then throw on false...

2019-02-01 06:04 UTC, martiniil commented on pilz_robot_programming/src/pilz_robot_programming/robot.py
> +                os.kill(pid, 0)
It has no symbolic name but is used to check if a process is running.
https://wiki.ubuntuusers.de/Signale/

2019-02-01 06:36 UTC, martiniil commented
I would like to squash some commits when you approved it.

2019-02-04 07:56 UTC, agutenkunst approved these changes

2019-02-04 07:56 UTC, merged